#include<bits/stdc++.h>
using namespace std;
int main()
{
    //freopen("input.txt","rt",stdin);
    //freopen("output.txt","w",stdout);
    int test;
    cin>>test;
    while(test--){
    string a,b,c,d,a1;
    stack<char>v1,v2,v3,v4;
    long long int bin1=0,bin2=0,dec1=0,dec2=0,j,k,p,l;
    cin>>a>>d>>a1;
    for(long long int i=a.size()-1; i>=0; i--)
    {
        if(a[i]=='0')
        {
            v1.push('0');
            v1.push('0');
            v1.push('0');
            v1.push('0');
        }
        if(a[i]=='1')
        {
            v1.push('1');
            v1.push('0');
            v1.push('0');
            v1.push('0');
        }
        if(a[i]=='2')
        {
            v1.push('0');
            v1.push('1');
            v1.push('0');
            v1.push('0');
        }
        if(a[i]=='3')
        {
            v1.push('1');
            v1.push('1');
            v1.push('0');
            v1.push('0');
        }
        if(a[i]=='4')
        {
            v1.push('0');
            v1.push('0');
            v1.push('1');
            v1.push('0');
        }
        if(a[i]=='5')
        {
            v1.push('1');
            v1.push('0');
            v1.push('1');
            v1.push('0');
        }
        if(a[i]=='6')
        {
            v1.push('0');
            v1.push('1');
            v1.push('1');
            v1.push('0');
        }
        if(a[i]=='7')
        {
            v1.push('1');
            v1.push('1');
            v1.push('1');
            v1.push('0');
        }
        if(a[i]=='8')
        {
            v1.push('0');
            v1.push('0');
            v1.push('0');
            v1.push('1');
        }
        if(a[i]=='9')
        {
            v1.push('1');
            v1.push('0');
            v1.push('0');
            v1.push('1');
        }
        if(a[i]=='A')
        {
            v1.push('0');
            v1.push('1');
            v1.push('0');
            v1.push('1');
        }
        if(a[i]=='B')
        {
            v1.push('1');
            v1.push('1');
            v1.push('0');
            v1.push('1');
        }
        if(a[i]=='C')
        {
            v1.push('0');
            v1.push('0');
            v1.push('1');
            v1.push('1');
        }
        if(a[i]=='D')
        {
            //("1101");
            v1.push('1');
            v1.push('0');
            v1.push('1');
            v1.push('1');
        }
        if(a[i]=='E')
        {
            //("1110");
            v1.push('0');
            v1.push('1');
            v1.push('1');
            v1.push('1');
        }
        if(a[i]=='F')
        {
            //("1111");
            v1.push('1');
            v1.push('1');
            v1.push('1');
            v1.push('1');
        }
    }
    for(long long int i=a1.size()-1; i>=0; i--)
    {
        if(a1[i]=='0')
        {
            //("0001");
            v2.push('0');
            v2.push('0');
            v2.push('0');
            v2.push('0');
        }
        if(a1[i]=='1')
        {
            //("0001");
            v2.push('1');
            v2.push('0');
            v2.push('0');
            v2.push('0');
        }
        if(a1[i]=='2')
        {
            //("0010");
            v2.push('0');
            v2.push('1');
            v2.push('0');
            v2.push('0');
        }
        if(a1[i]=='3')
        {
            //("0011");
            v2.push('1');
            v2.push('1');
            v2.push('0');
            v2.push('0');
        }
        if(a1[i]=='4')
        {
            //("0100");
            v2.push('0');
            v2.push('0');
            v2.push('1');
            v2.push('0');
        }
        if(a1[i]=='5')
        {
            //("0101");
            v2.push('1');
            v2.push('0');
            v2.push('1');
            v2.push('0');
        }
        if(a1[i]=='6')
        {
            //("0110");
            v2.push('0');
            v2.push('1');
            v2.push('1');
            v2.push('0');
        }
        if(a1[i]=='7')
        {
            //("0111");
            v2.push('1');
            v2.push('1');
            v2.push('1');
            v2.push('0');
        }
        if(a1[i]=='8')
        {
            //("1000");
            v2.push('0');
            v2.push('0');
            v2.push('0');
            v2.push('1');
        }
        if(a1[i]=='9')
        {
            //("1001");
            v2.push('1');
            v2.push('0');
            v2.push('0');
            v2.push('1');
        }
        if(a1[i]=='A')
        {
            //("1010");
            v2.push('0');
            v2.push('1');
            v2.push('0');
            v2.push('1');
        }
        if(a1[i]=='B')
        {
            //("1011");
            v2.push('1');
            v2.push('1');
            v2.push('0');
            v2.push('1');
        }
        if(a1[i]=='C')
        {
            //("1100");
            v2.push('0');
            v2.push('0');
            v2.push('1');
            v2.push('1');
        }
        if(a1[i]=='D')
        {
            //("1101");
            v2.push('1');
            v2.push('0');
            v2.push('1');
            v2.push('1');
        }
        if(a1[i]=='E')
        {
            //("1110");
            v2.push('0');
            v2.push('1');
            v2.push('1');
            v2.push('1');
        }
        if(a1[i]=='F')
        {
            //("1111");
            v2.push('1');
            v2.push('1');
            v2.push('1');
            v2.push('1');
        }
    }

    long long int  t=13-(v1.size());
    long long int t1=13-(v2.size());
    for(long long int i=0; i<t; i++)
        v1.push('0');
    v3=v1;
    for(long long int i=0; i<t1; i++)
        v2.push('0');
    v4=v2;
    while(!v3.empty())
    {
        char ch=v3.top();
        bin1=bin1*10+ch-'0';
        v3.pop();
    }
    while(!v4.empty())
    {
        char ch1=v4.top();
        bin2=bin2*10+ch1-'0';
        v4.pop();
    }
    long long int base=1;
    while(bin1!=0)
    {
        long long int rem=bin1%10;
        bin1/=10;
        dec1+=rem*base;
        // cout<<dec1<<endl;
        base=base*2;

    }
    long long int base2=1;
    while(bin2!=0)
    {
        long long int rem=bin2%10;
        bin2/=10;
        dec2+=rem*base2;

        base2=base2*2;


    }
    long long int res;
    if(d=="+")
        res=dec1+dec2;
    else
        res=dec1-dec2;
    while(!v1.empty())
    {
        cout<<v1.top();
        v1.pop();
    }
    cout<<" "<<d<<" ";
    for(long long int i=0; i<t1; i++)
        while(!v2.empty())
        {
            cout<<v2.top();
            v2.pop();
        }
    cout<<" "<<"="<<" "<<res<<endl;
    }
}
